### ISSUE TITLE
EXPORT AS SHAPEFILES not responding

### ISSUE THREAD

**Issue by GalPerelman** [modelcreate/epanet-to-gis#5]

**Comment by lbutler** [comment]
Hi @GalPerelman,

Are you able to provide more context? Is this with all files you're testing or just a single one? Can you let me know what browser you're working with and if possible could you send me the INP files so I can figure out what the issue is.

**Comment by GalPerelman** [comment]
Hi @lbutler 
I tried three files, the first one is a very simple net I created myself (I will send you by email)
When it didn't work I tried with net1 and net2 from EPANET examples 
I'm using chrome browser, and the EXPORT AS GEOJSON is working fine

**Comment by lbutler** [comment]
Thanks for sending me the INP file, I can see the same issue when I use that network, there appears to be an error thrown in the console. I will debug and release a new version when I can figure out what is causing the issue, many thanks for reporting this to me!

![image](https://user-images.githubusercontent.com/6113153/132871205-d8bb816b-c919-4b20-aa22-969d18ee3794.png)

**Comment by lbutler** [comment]
Are you able to try again @GalPerelman? I've just pushed and deployed a new version that should fix this bug, you might need to hard refresh to get the latest version (ctrl+F5 on chrome)

**Comment by lbutler** [comment]
Closing the issue but if there are any problems @GalPerelman, please let me know

**Comment by GalPerelman** [comment]
@lbutler 
For some reason, I didn't see the previous message of you pushed a new version
Checked again now and it is working great
